-- Add cv_is_generated column to profiles table
-- This tracks whether the user's CV was AI-generated vs uploaded
-- Used to show reminder banners encouraging users to upload their actual CV

ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS cv_is_generated BOOLEAN DEFAULT FALSE;

-- Add comment for documentation
COMMENT ON COLUMN profiles.cv_is_generated IS 'Whether the CV was generated by AI (true) or uploaded by user (false)';

-- Create index for efficient filtering (in case we want to query by this later)
CREATE INDEX IF NOT EXISTS idx_profiles_cv_is_generated ON profiles(cv_is_generated) WHERE cv_is_generated = TRUE;
